version: 2

sources:
  - name: weather_data
    database: de-zoomcamp-p3-gsod
    schema: weather_analysis
    tables:
      - name: weather_data_optimized
        description: "Optimized weather data from NOAA GSOD"
